version: '3.9'

networks:
  bitcoin-regtest-network:
    driver: bridge

services:
  bitcoin-regtest-node:
    image: ruimarinho/bitcoin-core:24.0.1 # TODO Build our own trusted Bitcoin Core Docker image instead of using ruimarinho's.
    container_name: bitcoin-regtest-node
    ports:
      - "18443:18443"
      - "18444:18444"
    networks:
      - bitcoin-regtest-network
    command:
      - -printtoconsole
      - -regtest=1
      - -rpcallowip=0.0.0.0/0
      - -rpcbind=0.0.0.0
      - -rpcuser=foo
      - -rpcpassword=rpcpassword
      - -fallbackfee=0.0001
      - -minrelaytxfee=0.00001
      - -maxtxfee=10000000
      - -txindex
      # - -debug=1
      # - -debug=rpc
      # - -debug=net
      # - -debug=mempool
      # - -debug=validation
    restart: always

  ord:
    container_name: ord
    build:
      context: .
    command:  ["--data-dir", "/index-data", "--bitcoin-rpc-url", "bitcoin-regtest-node:18443", "--regtest", "--bitcoin-rpc-password", "rpcpassword", "--bitcoin-rpc-username", "foo", "server", "--http-port", "8080"]
    volumes:
      - index_data:/index-data
    environment:
      - ORD_BITCOIN_RPC_USER=foo
      - ORD_BITCOIN_RPC_PASS=rpcpassword
      - ORD_BITCOIN_RPC_URL=http://bitcoin-regtest-node:18443
    ports:
      - "8080:8080"
    depends_on:
      - bitcoin-regtest-node
    networks:
      - bitcoin-regtest-network

volumes:
  bitcoin_data:
  index_data:

